# Generated by Django 3.2.3 on 2021-05-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_planner_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default=1, verbose_name='user name'),
            preserve_default=False,
        ),
    ]
