# Generated by Django 3.2.3 on 2021-05-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_planner_bot', '0002_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User model'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(default=0, verbose_name='user telegram ID'),
            preserve_default=False,
        ),
    ]
