# Generated by Django 3.2.3 on 2021-05-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_planner_bot', '0003_auto_20210531_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='event name')),
                ('description', models.TextField(verbose_name='event description')),
                ('subscribers', models.JSONField(verbose_name='subscribers IDs')),
                ('owner_ID', models.PositiveIntegerField(verbose_name='owner ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='', verbose_name='user full name'),
            preserve_default=False,
        ),
    ]
