# Generated by Django 3.2.3 on 2021-05-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_planner_bot', '0004_auto_20210531_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='user telegram ID'),
            preserve_default=False,
        ),
    ]
