# Generated by Django 3.2.3 on 2021-06-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_planner_bot', '0006_auto_20210601_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.PositiveIntegerField(verbose_name='user ID')),
                ('command', models.TextField(verbose_name='last command')),
            ],
        ),
    ]
