# Generated by Django 3.2.3 on 2021-06-02 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_planner_bot', '0007_activecommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2021, 6, 2), verbose_name='event start date'),
        ),
    ]
