# Generated by Django 3.2.3 on 2021-06-02 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_planner_bot', '0008_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 3, 10, 40, 325117), verbose_name='event start date'),
        ),
    ]
