# Generated by Django 3.2.3 on 2021-06-03 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_planner_bot', '0009_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ID', models.PositiveIntegerField(verbose_name='event ID')),
                ('owner_ID', models.PositiveIntegerField(verbose_name='owner ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 6, 4, 0, 1, 0, 267216), verbose_name='notification date')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 0, 1, 0, 266452), verbose_name='event start date'),
        ),
    ]
